global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notification'
receivers:
- name: 'email-notification'
  email_configs:
    - smarthost: 'mail1.gnuweeb.org:587'
      auth_username: 'zakir@gnuweeb.org'
      auth_password: '1Sampai8'
      from: 'zakir@gnuweeb.org'
      to: 'coderzakir44@gmail.com'
      headers:
        subject: 'Prometheus Mail Alerts'
      send_resolved: true
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']